export default [
    {
        "imgSrc": "img/design_msbsound.png",
        "title": "MAGIC STRAWBERRY SOUND 메인페이지 리디자인",
        "category": "Redesign",
        "lang": "Photoshop",
        "response": "Desktop",
        "info": "인디뮤직 레이블 MAGIC STRAWBERRY SOUND의 메인홈페이지를 리디자인하였습니다.",
        "concept": "개성적인, 다양한, 자유로운",
        "btn01": "기획서",
        "btn01_link": "plan/msbsound_renewal_designplan.pdf",
        "btn02": "와이어프레임 & 디자인시안",
        "btn02_link": "#",
        "btn03": "null",
        "btn03_link": "",
        "btn04": "null",
        "btn04_link": "",
        "tumbnail_size": "style='width: 100%; height: auto;'",
        "folder": "msbsound",
        "wireframe_imgs": ['msbsound_wireframe_390px.png', 'msbsound_wireframe_1920px.png'],
        "designSample_imgs": ['msbsound_designSample_390px.png', 'msbsound_designSample_1920px.png' ],
    },
    {
        "imgSrc": "img/design_SHIPDA_mockup.png",
        "title": "크리에이터 플랫폼 SHIPDA 기획 & 디자인",
        "category": "UX/UI Design",
        "lang": "Figma",
        "response": "Mobile App",
        "info": "가상의 크리에이터 플랫폼 'SHIPDA'를 전체 기획, 디자인하였습니다.",
        "concept": "독특한, 크리에이티브한, 깔끔한",
        "btn01": "기획서",
        "btn01_link": "plan/SHIPDA_designplan.pdf",
        "btn02": "null",
        "btn02_link": "",
        "btn03": "Figma Prototype",
        "btn03_link": "https://www.figma.com/proto/ocgzEwoiTET85uAdArIa9z/SHIPDA-PROTO?node-id=0-1&node-type=canvas&viewport=-232%2C284%2C0.04&t=SuMhuaNoMWYOc6OM-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=350%3A2602&show-proto-sidebar=1",
        "btn04": "null",
        "btn04_link": "",
        "tumbnail_size": "",
        "folder": "shipda",
        "wireframe_imgs": [],
        "designSample_imgs": [],
    },
]