export default [
    {
        "imgSrc": "img/Minji_Lee_portfolioSite_mockup.png",
        "title": "Minji Lee Portfolio Site",
        "category": "Original Website",
        "lang": "HTML, CSS, JavaScript",
        "response": "반응형 (Desktop, Tablet, Mobile)",
        "info": "개인 포트폴리오 웹사이트를 제작하였습니다.",
        "concept": "심플한, 귀여운, 감성적인",
        "plan": "기획서",
        "plan_link": "./plan/MinjiLee_portfolio_designplan.pdf",
        "btn02": "와이어프레임 & 디자인시안",
        "btn02_link": "#",
        "btn03": "null",
        "btn03_link": "",
        "btn04": "웹페이지",
        "btn04_link": "./index.html",
        "tumbnail_size": "",
        "folder": "portfolio",
        "wireframe_imgs": ['portfolio_wireframe_fullpage.png'],
        "designSample_imgs": ['portfolio_designSample_fullpage.png'],
    },
    {
        "imgSrc": "img/studiobones_mockup.png",
        "title": "studio bones 홈페이지",
        "category": "Original Website",
        "lang": "HTML, CSS, JQuery",
        "response": "반응형 (Desktop, Tablet, Mobile)",
        "info": "망원동 화실 'studio bones'의 홈페이지를  제작하였습니다.",
        "concept": "모던한, 심플한, 감성적인",
        "plan": "기획서",
        "plan_link": "./plan/studiobones_designplan.pdf",
        "btn02": "와이어프레임 & 디자인시안",
        "btn02_link": "#",
        "btn03": "null",
        "btn03_link": "",
        "btn04": "웹페이지",
        "btn04_link": "./web/personal_studio_bones/studiobones.html",
        "tumbnail_size": "",
        "folder": "studiobones",
        "wireframe_imgs": ['studiobones_wireframe_fullpage.png'],
        "designSample_imgs": ['studiobones_designsample_fullpage.png'],
    },
    {
        "imgSrc": "img/web_Ustore_promotionPage.png",
        "title": "티셔츠 기획전 이벤트 페이지",
        "category": "Original Website",
        "lang": "HTML, CSS, JQuery",
        "response": "고정형 (Desktop)",
        "info": "여름 티셔츠 기획전 프로모션 페이지를 제작하였습니다.",
        "concept": "독특한, 재밌는, 귀여운",
        "plan": "기획서",
        "plan_link": "plan/SUMMERT-SHIRTS_eventpage_designplan.pdf",
        "btn02": "와이어프레임 & 디자인시안",
        "btn02_link": "#",
        "btn03": "null",
        "btn03_link": "",
        "btn04": "웹페이지",
        "btn04_link": "./web/u_store_proto/u_store.html",
        "tumbnail_size": "style='width: 100%; height: auto;'",
        "folder": "u_store",
        "wireframe_imgs": ['u_store_wireframe_1920px.png'],
        "designSample_imgs": ['u_store_designSample_1920px.png'],
    },
    {
        "imgSrc": "img/web_grove_clonecoding_mockup.png",
        "title": "Grove 메인페이지",
        "category": "Clone Coding",
        "lang": "HTML, CSS, JavaScript, JQuery, Swiper Demo",
        "response": "고정형 (Desktop)",
        "info": "Grove의 메인홈페이지를 클론코딩하였습니다.",
        "concept": "-",
        "plan": "null",
        "plan_link": "",
        "btn02": "null",
        "btn02_link": "#",
        "btn03": "null",
        "btn03_link": "",
        "btn04": "웹페이지",
        "btn04_link": "./web/grove/grove.html",
        "tumbnail_size":"",
        "folder": "none",
        "wireframe_imgs": [],
        "designSample_imgs": [],
    },
]