export default [
    {
        "imgSrc": "img/Minji_Lee_portfolioSite.png",
        "title": "Minji Lee Portfolio Site",
        "category": "Original Website",
        "lang": "HTML, CSS, JavaScript",
        "response": "반응형 (Desktop, Tablet, Mobile)",
        "info": "개인 포트폴리오 웹사이트를 제작하였습니다.",
        "concept": "심플한, 귀여운, 감성적인",
        "btn01": "기획서",
        "btn01_link": "",
        "btn02": "와이어프레임",
        "btn02_link": "",
        "btn03": "디자인시안",
        "btn03_link": "",
        "btn04": "웹페이지",
        "btn04_link": "",
    },
    {
        "imgSrc": "img/studiobones_home.png",
        "title": "studio bones 홈페이지",
        "category": "Original Website",
        "lang": "HTML, CSS, JavaScript",
        "response": "Desktop",
        "info": "망원동 화실 'studio bones'의 홈페이지를 제작하였습니다.",
        "concept": "모던한, 심플한, 감성적인",
        "btn01": "기획서",
        "btn01_link": "",
        "btn02": "와이어프레임",
        "btn02_link": "",
        "btn03": "디자인시안",
        "btn03_link": "",
        "btn04": "웹페이지",
        "btn04_link": "personal_studio_bones/index.html",
        "tumbnail_size": "style='height: 100%; width: auto;'"
    },
    {
        "imgSrc": "img/web_Ustore_promotionPage.png",
        "title": "티셔츠 기획전 이벤트 페이지",
        "category": "Original Website",
        "lang": "HTML, CSS, JQuery",
        "response": "고정형 (Desktop)",
        "info": "여름 티셔츠 기획전 프로모션 페이지를 제작하였습니다.",
        "concept": "독특한, 재밌는, 귀여운",
        "btn01": "기획서",
        "btn01_link": "",
        "btn02": "와이어프레임",
        "btn02_link": "",
        "btn03": "디자인시안",
        "btn03_link": "",
        "btn04": "웹페이지",
        "btn04_link": "u_store_proto/index.html",
    },
    {
        "imgSrc": "img/web_grove_clonecoding.png",
        "title": "Grove 메인페이지",
        "category": "Clone Coding",
        "lang": "HTML, CSS, JavaScript, Jquery, Swiper Demo",
        "response": "고정형 (Desktop)",
        "info": "Grove의 메인홈페이지를 클론코딩으로 구축하였습니다.",
        "concept": "x",
        "btn01": "null",
        "btn01_link": "",
        "btn02": "null",
        "btn02_link": "",
        "btn03": "null",
        "btn03_link": "",
        "btn04": "웹페이지",
        "btn04_link": "grove/index.html",
    },
]